#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MODEL_PATH="${MODEL_PATH:-checkpoints/shoppingbench-sft/qwen3-4b_state_folded_4xa800_full_sft_lr1e-5_micro2_20260628_1139/global_step_256}"
export PROJECT_NAME="${PROJECT_NAME:-shoppingbench-rl}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo_qwen3-4b_state_folded_a800_from_sft_step256}"

export TRAIN_FILES="${TRAIN_FILES:-dataset/shoppingbench_query/train.parquet}"
export VAL_FILES="${VAL_FILES:-dataset/shoppingbench_query/test.parquet}"

export NGPUS_PER_NODE="${NGPUS_PER_NODE:-4}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-8}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-8}"
export PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"

export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-4096}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-32768}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-12288}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-12288}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-16}"
export ROLLOUT_N="${ROLLOUT_N:-4}"
export ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-1.0}"
export ROLLOUT_TOP_P="${ROLLOUT_TOP_P:-0.9}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.55}"
export ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="${ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE:-1}"
export ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-False}"
export ROLLOUT_FREE_CACHE_ENGINE="${ROLLOUT_FREE_CACHE_ENGINE:-False}"
export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-8}"

export MAX_ASSISTANT_TURNS="${MAX_ASSISTANT_TURNS:-12}"
export MAX_USER_TURNS="${MAX_USER_TURNS:-12}"
export MAX_PARALLEL_CALLS="${MAX_PARALLEL_CALLS:-4}"
export MAX_TOOL_RESPONSE_LENGTH="${MAX_TOOL_RESPONSE_LENGTH:-256}"
export STATE_MAX_CANDIDATES_PER_SEARCH="${STATE_MAX_CANDIDATES_PER_SEARCH:-10}"
export STATE_MAX_SEARCHES="${STATE_MAX_SEARCHES:-12}"
export STATE_MAX_BUDGET_CANDIDATES="${STATE_MAX_BUDGET_CANDIDATES:-120}"
export STATE_MAX_VIEWED_PRODUCTS="${STATE_MAX_VIEWED_PRODUCTS:-40}"
export STATE_NEVER_EXPAND="${STATE_NEVER_EXPAND:-False}"
export STATE_MIN_CHAR_SAVING="${STATE_MIN_CHAR_SAVING:-0.0}"
export SYSTEM_PROMPT_FILE="${SYSTEM_PROMPT_FILE:-src/agent/prompt/rollout.state_local.md}"

export ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-flash_attention_2}"
export USE_REMOVE_PADDING="${USE_REMOVE_PADDING:-False}"
export REF_PARAM_OFFLOAD="${REF_PARAM_OFFLOAD:-True}"
export ACTOR_OPTIMIZER_OFFLOAD="${ACTOR_OPTIMIZER_OFFLOAD:-True}"
export ACTOR_OPTIMIZER_FOREACH="${ACTOR_OPTIMIZER_FOREACH:-false}"
export ACTOR_FSDP_MODEL_DTYPE="${ACTOR_FSDP_MODEL_DTYPE:-bf16}"
export ENTROPY_FROM_LOGITS_WITH_CHUNKING="${ENTROPY_FROM_LOGITS_WITH_CHUNKING:-True}"
export LEARNING_RATE="${LEARNING_RATE:-1e-6}"
export ENTROPY_COEFF="${ENTROPY_COEFF:-0}"
export USE_KL_LOSS="${USE_KL_LOSS:-False}"

export TOTAL_EPOCHS="${TOTAL_EPOCHS:-3}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"
export SAVE_FREQ="${SAVE_FREQ:-50}"
export TEST_FREQ="${TEST_FREQ:-50}"
export LOGGER="${LOGGER:-console}"
export ROLLOUT_DATA_DIR="${ROLLOUT_DATA_DIR:-rollouts/${EXPERIMENT_NAME}/train}"
export VALIDATION_DATA_DIR="${VALIDATION_DATA_DIR:-rollouts/${EXPERIMENT_NAME}/validation}"
export SEARCH_SERVER_URL="${SEARCH_SERVER_URL:-http://127.0.0.1:5631/}"
export REQUIRE_SEARCH_SERVER="${REQUIRE_SEARCH_SERVER:-1}"
export DRY_RUN="${DRY_RUN:-0}"

if [ "$DRY_RUN" = "1" ]; then
  cat <<EOF
MODEL_PATH=${MODEL_PATH}
PROJECT_NAME=${PROJECT_NAME}
EXPERIMENT_NAME=${EXPERIMENT_NAME}
TRAIN_FILES=${TRAIN_FILES}
VAL_FILES=${VAL_FILES}
NGPUS_PER_NODE=${NGPUS_PER_NODE}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE}
VAL_BATCH_SIZE=${VAL_BATCH_SIZE}
ROLLOUT_N=${ROLLOUT_N}
ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION}
ROLLOUT_ENFORCE_EAGER=${ROLLOUT_ENFORCE_EAGER}
ROLLOUT_FREE_CACHE_ENGINE=${ROLLOUT_FREE_CACHE_ENGINE}
ACTOR_FSDP_MODEL_DTYPE=${ACTOR_FSDP_MODEL_DTYPE}
MAX_ASSISTANT_TURNS=${MAX_ASSISTANT_TURNS}
MAX_USER_TURNS=${MAX_USER_TURNS}
MAX_PARALLEL_CALLS=${MAX_PARALLEL_CALLS}
STATE_MAX_CANDIDATES_PER_SEARCH=${STATE_MAX_CANDIDATES_PER_SEARCH}
STATE_MAX_SEARCHES=${STATE_MAX_SEARCHES}
STATE_MAX_BUDGET_CANDIDATES=${STATE_MAX_BUDGET_CANDIDATES}
STATE_MAX_VIEWED_PRODUCTS=${STATE_MAX_VIEWED_PRODUCTS}
STATE_NEVER_EXPAND=${STATE_NEVER_EXPAND}
STATE_MIN_CHAR_SAVING=${STATE_MIN_CHAR_SAVING}
SYSTEM_PROMPT_FILE=${SYSTEM_PROMPT_FILE:-src/agent/prompt/rollout.state_local.md}
SEARCH_SERVER_URL=${SEARCH_SERVER_URL}
REQUIRE_SEARCH_SERVER=${REQUIRE_SEARCH_SERVER}
EOF
  exit 0
fi

if [ "$REQUIRE_SEARCH_SERVER" = "1" ]; then
  if ! curl --noproxy "127.0.0.1,localhost" -fsS "$SEARCH_SERVER_URL" >/dev/null 2>&1; then
    echo "[ERROR] ShoppingBench search server is not reachable: ${SEARCH_SERVER_URL}" >&2
    echo "[HINT] Start it before RL, for example:" >&2
    echo "  JAVA_HOME=/root/.local/jdks/temurin-21 PATH=/root/.local/jdks/temurin-21/bin:/root/miniconda3/envs/shoppingbench/bin:\\$PATH INDEX_DIR=indexes PORT=5631 /root/miniconda3/envs/shoppingbench/bin/python src/search_engine/server.py" >&2
    exit 1
  fi
fi

exec "${SCRIPT_DIR}/run_grpo_qwen3_1_7b_query_verl.sh" "$@"
