#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MODEL_PATH="${MODEL_PATH:-checkpoints/shoppingbench-sft/qwen3-4b_state_folded_4xa800_full_sft_lr1e-5_micro2_20260628_1139/global_step_256}"
export PROJECT_NAME="${PROJECT_NAME:-shoppingbench-smoke}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo_qwen3-4b_state_folded_lora_smoke_from_step256}"
export TRAIN_FILES="${TRAIN_FILES:-dataset/smoke/query_train_2.parquet}"
export VAL_FILES="${VAL_FILES:-dataset/smoke/query_val_1.parquet}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-2}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-1}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-128}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-2}"
export PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-4096}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-4096}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-4096}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-2}"
export ROLLOUT_N="${ROLLOUT_N:-2}"
export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-1}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.45}"
export MAX_ASSISTANT_TURNS="${MAX_ASSISTANT_TURNS:-2}"
export MAX_USER_TURNS="${MAX_USER_TURNS:-2}"
export MAX_TOOL_RESPONSE_LENGTH="${MAX_TOOL_RESPONSE_LENGTH:-128}"
export LORA_RANK="${LORA_RANK:-8}"
export LORA_ALPHA="${LORA_ALPHA:-16}"
export TARGET_MODULES="${TARGET_MODULES:-all-linear}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-1}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-1}"
export SAVE_FREQ="${SAVE_FREQ:--1}"
export TEST_FREQ="${TEST_FREQ:--1}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-False}"
export ROLLOUT_DATA_DIR="${ROLLOUT_DATA_DIR:-rollouts/smoke/grpo_qwen3_4b_state_folded_lora_1step}"
export VALIDATION_DATA_DIR="${VALIDATION_DATA_DIR:-rollouts/smoke/grpo_qwen3_4b_state_folded_lora_validation_1step}"

exec "${SCRIPT_DIR}/run_grpo_qwen3_4b_state_folded_a800.sh" \
  data.dataloader_num_workers=0 \
  "$@"
