#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MODEL_PATH="${MODEL_PATH:-checkpoints/shoppingbench-sft/sft_clean924_prefix_len10240_full_3ep_20260709_043231/global_step_108}"
export PROJECT_NAME="${PROJECT_NAME:-shoppingbench-rl}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo_qwen3-4b_outcome_only_from_sft_step108}"

export TRAIN_FILES="${TRAIN_FILES:-dataset/shoppingbench_query_rl_v2/train.parquet}"
export VAL_FILES="${VAL_FILES:-dataset/shoppingbench_query_rl_v2/validation.parquet}"

export NGPUS_PER_NODE="${NGPUS_PER_NODE:-2}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-8}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-8}"
export PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-1}"
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-1}"

export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-10240}"
# 32768 OOMed before the first optimizer step in the Step108 pilot smoke test.
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-12288}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-12288}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-12288}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-8}"
export ROLLOUT_APPLY_MAX_NUM_SEQS="${ROLLOUT_APPLY_MAX_NUM_SEQS:-True}"
export ROLLOUT_ENABLE_PREFIX_CACHING="${ROLLOUT_ENABLE_PREFIX_CACHING:-True}"
export ROLLOUT_N="${ROLLOUT_N:-8}"
# Locked by the Step108 outcome-only sampling search (2026-07-10).
# Explicit environment overrides remain available as a reversible fallback.
export TRAIN_ROLLOUT_TEMPERATURE="${TRAIN_ROLLOUT_TEMPERATURE:-${ROLLOUT_TEMPERATURE:-0.4}}"
export TRAIN_ROLLOUT_TOP_P="${TRAIN_ROLLOUT_TOP_P:-${ROLLOUT_TOP_P:-0.95}}"
export VAL_ROLLOUT_TEMPERATURE="${VAL_ROLLOUT_TEMPERATURE:-0.2}"
export VAL_ROLLOUT_TOP_P="${VAL_ROLLOUT_TOP_P:-0.9}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.55}"
export ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE="${ROLLOUT_TENSOR_MODEL_PARALLEL_SIZE:-1}"
export ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-False}"
export ROLLOUT_FREE_CACHE_ENGINE="${ROLLOUT_FREE_CACHE_ENGINE:-False}"
export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-8}"
export STABLE_ROLLOUT_SAMPLING="${STABLE_ROLLOUT_SAMPLING:-True}"
export STABLE_ROLLOUT_SEED_REQUESTS="${STABLE_ROLLOUT_SEED_REQUESTS:-True}"
export STABLE_ROLLOUT_DETERMINISTIC_REQUEST_ID="${STABLE_ROLLOUT_DETERMINISTIC_REQUEST_ID:-True}"
export STABLE_ROLLOUT_STABLE_SERVER_ORDER="${STABLE_ROLLOUT_STABLE_SERVER_ORDER:-True}"
export STABLE_ROLLOUT_STABLE_SERVER_ROUTING="${STABLE_ROLLOUT_STABLE_SERVER_ROUTING:-True}"
export STABLE_ROLLOUT_SEED_BASE="${STABLE_ROLLOUT_SEED_BASE:-0}"
export STABLE_ROLLOUT_OFFSET_BASE="${STABLE_ROLLOUT_OFFSET_BASE:-0}"
export STABLE_ROLLOUT_FORCE_GENERATION_CONFIG_N1="${STABLE_ROLLOUT_FORCE_GENERATION_CONFIG_N1:-True}"

export MAX_ASSISTANT_TURNS="${MAX_ASSISTANT_TURNS:-15}"
export MAX_USER_TURNS="${MAX_USER_TURNS:-15}"
export MAX_PARALLEL_CALLS="${MAX_PARALLEL_CALLS:-4}"
export MAX_TOOL_RESPONSE_LENGTH="${MAX_TOOL_RESPONSE_LENGTH:-256}"
export STATE_MAX_CANDIDATES_PER_SEARCH="${STATE_MAX_CANDIDATES_PER_SEARCH:-10}"
export STATE_MAX_SEARCHES="${STATE_MAX_SEARCHES:-12}"
export STATE_MAX_BUDGET_CANDIDATES="${STATE_MAX_BUDGET_CANDIDATES:-120}"
export STATE_MAX_VIEWED_PRODUCTS="${STATE_MAX_VIEWED_PRODUCTS:-40}"
export STATE_NEVER_EXPAND="${STATE_NEVER_EXPAND:-False}"
export STATE_MIN_CHAR_SAVING="${STATE_MIN_CHAR_SAVING:-0.0}"
export SYSTEM_PROMPT_FILE="${SYSTEM_PROMPT_FILE:-src/agent/prompt/rollout.state_local.md}"

export ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-flash_attention_2}"
export USE_REMOVE_PADDING="${USE_REMOVE_PADDING:-False}"
export REF_PARAM_OFFLOAD="${REF_PARAM_OFFLOAD:-True}"
export ACTOR_OPTIMIZER_OFFLOAD="${ACTOR_OPTIMIZER_OFFLOAD:-True}"
export ACTOR_OPTIMIZER_FOREACH="${ACTOR_OPTIMIZER_FOREACH:-false}"
export ACTOR_FSDP_MODEL_DTYPE="${ACTOR_FSDP_MODEL_DTYPE:-bf16}"
export ENTROPY_FROM_LOGITS_WITH_CHUNKING="${ENTROPY_FROM_LOGITS_WITH_CHUNKING:-True}"
export LEARNING_RATE="${LEARNING_RATE:-1e-6}"
export ENTROPY_COEFF="${ENTROPY_COEFF:-0}"
export USE_KL_LOSS="${USE_KL_LOSS:-False}"
export SHOPPINGBENCH_REWARD_MODE="${SHOPPINGBENCH_REWARD_MODE:-asr_terminal}"
export SHOPPINGBENCH_ASR_EMBEDDING_DEVICE="${SHOPPINGBENCH_ASR_EMBEDDING_DEVICE:-cpu}"

export TOTAL_EPOCHS="${TOTAL_EPOCHS:-3}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-200}"
export SAVE_FREQ="${SAVE_FREQ:-50}"
export TEST_FREQ="${TEST_FREQ:-50}"
export LOGGER="${LOGGER:-console}"
export ROLLOUT_DATA_DIR="${ROLLOUT_DATA_DIR:-rollouts/${EXPERIMENT_NAME}/train}"
export VALIDATION_DATA_DIR="${VALIDATION_DATA_DIR:-rollouts/${EXPERIMENT_NAME}/validation}"
export SEARCH_SERVER_URL="${SEARCH_SERVER_URL:-http://127.0.0.1:5631/}"
export REQUIRE_SEARCH_SERVER="${REQUIRE_SEARCH_SERVER:-1}"
export DRY_RUN="${DRY_RUN:-0}"

if [ "$DRY_RUN" = "1" ]; then
  cat <<EOF
MODEL_PATH=${MODEL_PATH}
PROJECT_NAME=${PROJECT_NAME}
EXPERIMENT_NAME=${EXPERIMENT_NAME}
TRAIN_FILES=${TRAIN_FILES}
VAL_FILES=${VAL_FILES}
NGPUS_PER_NODE=${NGPUS_PER_NODE}
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE}
GEN_BATCH_SIZE=${GEN_BATCH_SIZE:-$TRAIN_BATCH_SIZE}
DYNAMIC_SAMPLING_ENABLE=${DYNAMIC_SAMPLING_ENABLE:-False}
DYNAMIC_SAMPLING_METRIC=${DYNAMIC_SAMPLING_METRIC:-terminal_asr}
MAX_NUM_GEN_BATCHES=${MAX_NUM_GEN_BATCHES:-0}
VAL_BATCH_SIZE=${VAL_BATCH_SIZE}
MAX_RESPONSE_LENGTH=${MAX_RESPONSE_LENGTH}
PPO_MAX_TOKEN_LEN_PER_GPU=${PPO_MAX_TOKEN_LEN_PER_GPU}
ROLLOUT_N=${ROLLOUT_N}
TRAIN_ROLLOUT_TEMPERATURE=${TRAIN_ROLLOUT_TEMPERATURE}
TRAIN_ROLLOUT_TOP_P=${TRAIN_ROLLOUT_TOP_P}
VAL_ROLLOUT_TEMPERATURE=${VAL_ROLLOUT_TEMPERATURE}
VAL_ROLLOUT_TOP_P=${VAL_ROLLOUT_TOP_P}
ROLLOUT_MAX_NUM_SEQS=${ROLLOUT_MAX_NUM_SEQS}
ROLLOUT_APPLY_MAX_NUM_SEQS=${ROLLOUT_APPLY_MAX_NUM_SEQS}
ROLLOUT_ENABLE_PREFIX_CACHING=${ROLLOUT_ENABLE_PREFIX_CACHING}
ROLLOUT_MAX_MODEL_LEN=${ROLLOUT_MAX_MODEL_LEN}
ROLLOUT_GPU_MEMORY_UTILIZATION=${ROLLOUT_GPU_MEMORY_UTILIZATION}
ROLLOUT_ENFORCE_EAGER=${ROLLOUT_ENFORCE_EAGER}
ROLLOUT_FREE_CACHE_ENGINE=${ROLLOUT_FREE_CACHE_ENGINE}
STABLE_ROLLOUT_SAMPLING=${STABLE_ROLLOUT_SAMPLING}
STABLE_ROLLOUT_SEED_REQUESTS=${STABLE_ROLLOUT_SEED_REQUESTS}
STABLE_ROLLOUT_DETERMINISTIC_REQUEST_ID=${STABLE_ROLLOUT_DETERMINISTIC_REQUEST_ID}
STABLE_ROLLOUT_STABLE_SERVER_ORDER=${STABLE_ROLLOUT_STABLE_SERVER_ORDER}
STABLE_ROLLOUT_STABLE_SERVER_ROUTING=${STABLE_ROLLOUT_STABLE_SERVER_ROUTING}
STABLE_ROLLOUT_SEED_BASE=${STABLE_ROLLOUT_SEED_BASE}
STABLE_ROLLOUT_OFFSET_BASE=${STABLE_ROLLOUT_OFFSET_BASE}
STABLE_ROLLOUT_FORCE_GENERATION_CONFIG_N1=${STABLE_ROLLOUT_FORCE_GENERATION_CONFIG_N1}
ENGINE_GENERATION_N=1
SHOPPINGBENCH_REWARD_MODE=${SHOPPINGBENCH_REWARD_MODE}
ACTOR_FSDP_MODEL_DTYPE=${ACTOR_FSDP_MODEL_DTYPE}
MAX_ASSISTANT_TURNS=${MAX_ASSISTANT_TURNS}
MAX_USER_TURNS=${MAX_USER_TURNS}
MAX_PARALLEL_CALLS=${MAX_PARALLEL_CALLS}
STATE_MAX_CANDIDATES_PER_SEARCH=${STATE_MAX_CANDIDATES_PER_SEARCH}
STATE_MAX_SEARCHES=${STATE_MAX_SEARCHES}
STATE_MAX_BUDGET_CANDIDATES=${STATE_MAX_BUDGET_CANDIDATES}
STATE_MAX_VIEWED_PRODUCTS=${STATE_MAX_VIEWED_PRODUCTS}
STATE_NEVER_EXPAND=${STATE_NEVER_EXPAND}
STATE_MIN_CHAR_SAVING=${STATE_MIN_CHAR_SAVING}
SYSTEM_PROMPT_FILE=${SYSTEM_PROMPT_FILE:-src/agent/prompt/rollout.state_local.md}
SEARCH_SERVER_URL=${SEARCH_SERVER_URL}
REQUIRE_SEARCH_SERVER=${REQUIRE_SEARCH_SERVER}
EOF
  exit 0
fi

if [ "$REQUIRE_SEARCH_SERVER" = "1" ]; then
  if ! curl --noproxy "127.0.0.1,localhost" -fsS "$SEARCH_SERVER_URL" >/dev/null 2>&1; then
    echo "[ERROR] ShoppingBench search server is not reachable: ${SEARCH_SERVER_URL}" >&2
    echo "[HINT] Start it before RL, for example:" >&2
    echo "  JAVA_HOME=/root/.local/jdks/temurin-21 PATH=/root/.local/jdks/temurin-21/bin:/root/miniconda3/envs/shoppingbench/bin:\\$PATH INDEX_DIR=indexes PORT=5631 /root/miniconda3/envs/shoppingbench/bin/python src/search_engine/server.py" >&2
    exit 1
  fi
fi

exec "${SCRIPT_DIR}/run_grpo_qwen3_1_7b_query_verl.sh" "$@"
