#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

export EXPERIMENT_NAME="${EXPERIMENT_NAME:-grpo_qwen3-4b_outcome_only_g4_large_batch_20260709}"
export MODEL_PATH="${MODEL_PATH:-${ROOT_DIR}/checkpoints/shoppingbench-sft/sft_clean924_prefix_len10240_full_3ep_20260709_043231/global_step_108}"

export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-10240}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-24}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-8}"
export PPO_MINI_BATCH_SIZE="${PPO_MINI_BATCH_SIZE:-24}"
export PPO_MICRO_BATCH_SIZE_PER_GPU="${PPO_MICRO_BATCH_SIZE_PER_GPU:-4}"
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}"
export PPO_MAX_TOKEN_LEN_PER_GPU="${PPO_MAX_TOKEN_LEN_PER_GPU:-65536}"

export ROLLOUT_N="${ROLLOUT_N:-4}"
export ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-0.2}"
export ROLLOUT_TOP_P="${ROLLOUT_TOP_P:-0.9}"
export ROLLOUT_AGENT_NUM_WORKERS="${ROLLOUT_AGENT_NUM_WORKERS:-16}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-8}"
export ROLLOUT_APPLY_MAX_NUM_SEQS="${ROLLOUT_APPLY_MAX_NUM_SEQS:-True}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-32768}"
export ROLLOUT_MAX_MODEL_LEN="${ROLLOUT_MAX_MODEL_LEN:-12288}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.70}"

export TOTAL_EPOCHS="${TOTAL_EPOCHS:-2}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-56}"
export SAVE_FREQ="${SAVE_FREQ:-14}"
export TEST_FREQ="${TEST_FREQ:-14}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-True}"

export USE_KL_LOSS="${USE_KL_LOSS:-False}"
export ENTROPY_COEFF="${ENTROPY_COEFF:-0}"
export SHOPPINGBENCH_PROTOCOL_WEIGHT_START="${SHOPPINGBENCH_PROTOCOL_WEIGHT_START:-0}"
export SHOPPINGBENCH_PROTOCOL_ANNEAL_STEPS="${SHOPPINGBENCH_PROTOCOL_ANNEAL_STEPS:-0}"
export SHOPPINGBENCH_PROTOCOL_ANNEAL_FRACTION="${SHOPPINGBENCH_PROTOCOL_ANNEAL_FRACTION:-0}"
export SHOPPINGBENCH_STEP_PENALTY="${SHOPPINGBENCH_STEP_PENALTY:-0}"
export SHOPPINGBENCH_REWARD_MODE="${SHOPPINGBENCH_REWARD_MODE:-asr_terminal}"

exec bash src/rl/run_grpo_qwen3_4b_state_folded_a800.sh \
  actor_rollout_ref.actor.clip_ratio=0.2 \
  actor_rollout_ref.actor.clip_ratio_low=0.2 \
  actor_rollout_ref.actor.clip_ratio_high=0.28 \
  "$@"
