# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import asyncio
import json
import logging
import os
import sys
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any
from uuid import uuid4

import regex as re
from pydantic import BaseModel

from verl.experimental.agent_loop.agent_loop import AgentLoopBase, AgentLoopOutput
from verl.tools.utils.tool_registry import initialize_tools_from_config
from verl.utils.profiler import simple_timer
from verl.utils.rollout_trace import rollout_trace_op

AGENT_SRC = Path(__file__).resolve().parents[4] / "agent"
if str(AGENT_SRC) not in sys.path:
    sys.path.insert(0, str(AGENT_SRC))

from util.harness_fsm import (  # noqa: E402
    STATE_CANDIDATE_SELECT,
    build_harness_snapshot,
    build_compact_harness_user_prompt,
    is_duplicate_find_product_in_turn,
    is_repeated_failed_search,
    is_repeated_search,
)
from util.message import ASSISTANT_ROLES, USER_ROLES, Message, generate_tool_call_id  # noqa: E402
from util.system_prompt import build_system_prompt  # noqa: E402

logger = logging.getLogger(__file__)
logger.setLevel(os.getenv("VERL_LOGGING_LEVEL", "WARN"))

FSM_SYSTEM_PROMPT = (
    "You are a ShoppingBench agent. Read the latest <state> JSON and output exactly one "
    "<think> block followed by exactly one <tool_call> JSON array. Only tools listed "
    "in allowed_tools are valid."
)

BUDGET_CHECK_TOOL_SCHEMA = {
    "type": "function",
    "function": {
        "name": "budget_check",
        "description": "Compute voucher-adjusted budget from selected product ids, observed candidate prices, and the agent's structured voucher interpretation.",
        "parameters": {
            "type": "object",
            "properties": {
                "product_ids": {"type": "array", "description": "Selected product ids from candidate_pool."},
                "voucher": {"type": "object", "description": "Structured interpretation of the user's voucher."},
                "budget": {"type": "number", "description": "User budget parsed by the agent from the query."},
            },
            "required": ["product_ids", "voucher", "budget"],
        },
    },
}


class FunctionCall(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ToolParser(ABC):
    @abstractmethod
    async def extract_tool_calls(self, responses_ids: list[int]) -> list[FunctionCall]:
        """Extract tool calls from the responses.

        Args:
            responses_ids (List[int]): The ids of the responses.

        Returns:
            List[FunctionCall]: The extracted tool calls.
        """
        raise NotImplementedError


class HermesToolParser(ToolParser):
    """Adapted from https://github.com/vllm-project/vllm/blob/v0.9.1/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py"""

    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer

        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.tool_call_regex = re.compile(r"<tool_call>(.*?)</tool_call>", re.DOTALL)

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> list[FunctionCall]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        if self.tool_call_start_token not in text or self.tool_call_end_token not in text:
            return []

        matches = self.tool_call_regex.findall(text)
        function_calls = []
        for match in matches:
            try:
                function_call = json.loads(match)
                name, arguments = function_call["name"], function_call["arguments"]
                function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
            except Exception as e:
                logger.error(f"Failed to decode tool call: {e}")
        return function_calls


class ShoppingBenchXMLToolParser(ToolParser):
    def __init__(self, tokenizer) -> None:
        self.tokenizer = tokenizer
        self.tool_call_regex = re.compile(r"<tool_call>(.*?)</tool_call>", re.DOTALL)

    @rollout_trace_op
    async def extract_tool_calls(self, responses_ids: list[int]) -> list[FunctionCall]:
        loop = asyncio.get_running_loop()
        text = await loop.run_in_executor(None, self.tokenizer.decode, responses_ids)
        matches = self.tool_call_regex.findall(text)
        function_calls = []
        for match in matches:
            try:
                parsed = json.loads(match.strip())
            except Exception as e:
                logger.error(f"Failed to decode ShoppingBench tool call: {e}")
                continue
            if not isinstance(parsed, list):
                continue
            for call in parsed:
                if not isinstance(call, dict):
                    continue
                if set(call.keys()) != {"name", "parameters"}:
                    continue
                name = call.get("name")
                arguments = call.get("parameters") or {}
                if isinstance(name, str) and isinstance(arguments, dict):
                    function_calls.append(FunctionCall(name=name, arguments=json.dumps(arguments, ensure_ascii=False)))
        return function_calls


class ToolAgentLoop(AgentLoopBase):
    def __init__(self, config, server_manager, tokenizer):
        super().__init__(config, server_manager, tokenizer)

    @classmethod
    def init_class(cls, config, tokenizer):
        if cls._class_initialized:
            return
        cls._class_initialized = True
        print("Performing class-level ToolAgentLoop initialization")

        # Initialize tools from config file
        cls.tokenizer = tokenizer
        cls.max_user_turns = config.actor_rollout_ref.rollout.multi_turn.max_user_turns
        cls.max_assistant_turns = config.actor_rollout_ref.rollout.multi_turn.max_assistant_turns
        cls.max_parallel_calls = config.actor_rollout_ref.rollout.multi_turn.max_parallel_calls
        cls.max_tool_response_length = config.actor_rollout_ref.rollout.multi_turn.max_tool_response_length
        cls.tool_response_truncate_side = config.actor_rollout_ref.rollout.multi_turn.tool_response_truncate_side
        tool_config_path = config.actor_rollout_ref.rollout.multi_turn.tool_config_path
        tool_list = initialize_tools_from_config(tool_config_path) if tool_config_path else []
        cls.tools = {tool.name: tool for tool in tool_list}
        cls.tool_schemas = [tool.tool_schema.model_dump(exclude_unset=True, exclude_none=True) for tool in tool_list]
        if "budget_check" not in {schema.get("function", {}).get("name") for schema in cls.tool_schemas}:
            cls.tool_schemas.append(BUDGET_CHECK_TOOL_SCHEMA)
        cls.tool_parser = cls.get_tool_parser(config.actor_rollout_ref.rollout.multi_turn.format)
        print(f"Initialized tools: {cls.tools}")

        cls.prompt_length = config.actor_rollout_ref.rollout.prompt_length
        cls.response_length = config.actor_rollout_ref.rollout.response_length
        cls.system_prompt = tokenizer.apply_chat_template([{}], add_generation_prompt=False, tokenize=True)
        cls.state_max_candidates_per_search = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_max_candidates_per_search", 10
        )
        cls.state_max_searches = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_max_searches", None
        )
        cls.state_max_budget_candidates = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_max_budget_candidates", None
        )
        cls.state_max_viewed_products = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_max_viewed_products", None
        )
        cls.state_never_expand = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_never_expand", False
        )
        cls.state_min_char_saving = config.actor_rollout_ref.rollout.multi_turn.get(
            "state_min_char_saving", 0.0
        )
        system_prompt_file = config.actor_rollout_ref.rollout.multi_turn.get("system_prompt_file", None)
        if system_prompt_file in (None, "", "null", "None"):
            cls.runtime_system_prompt = None
        else:
            cls.runtime_system_prompt = build_system_prompt(
                str(system_prompt_file),
                exclude_tools={"web_search", "python_execute"},
            )

    @rollout_trace_op
    async def run(self, messages: list[dict[str, Any]], sampling_params: dict[str, Any]) -> AgentLoopOutput:
        metrics = {}
        request_id = uuid4().hex
        system_message = self._system_message(messages)
        query = self._initial_user_query(messages)
        history_messages = [Message(user=query).to_string(USER_ROLES)]
        active_snapshot = self._state_local_snapshot(
            build_harness_snapshot(history_messages, allow_legacy_python_budget=False)
        )
        user_prompt = self._compact_state_prompt(active_snapshot, history_messages)
        current_messages = [system_message, {"role": "user", "content": user_prompt}]
        prompt_ids = await self.loop.run_in_executor(
            None,
            lambda: self.tokenizer.apply_chat_template(current_messages, add_generation_prompt=True, tokenize=True),
        )
        response_mask = []
        rollout_messages: list[dict[str, Any]] = [*current_messages]

        user_turns, assistant_turns = 0, 0
        while True:
            generation_sampling_params = self._sampling_params_for_remaining_response(
                sampling_params,
                used_response_tokens=len(response_mask),
            )
            if generation_sampling_params is None:
                break
            with simple_timer("generate_sequences", metrics):
                response_ids = await self.server_manager.generate(
                    request_id=request_id, prompt_ids=prompt_ids, sampling_params=generation_sampling_params
                )
            prompt_ids += response_ids
            response_mask += [1] * len(response_ids)
            assistant_turns += 1

            # reach max response length
            if len(response_mask) >= self.response_length:
                break

            # reach max assistant turns
            if self.max_assistant_turns and assistant_turns >= self.max_assistant_turns:
                break

            # reach max user turns
            if self.max_user_turns and user_turns >= self.max_user_turns:
                break

            assistant_text = await self.loop.run_in_executor(None, self.tokenizer.decode, response_ids)
            assistant_record = {"role": "assistant", "content": assistant_text}
            tool_block_error = self._tool_block_validation_error(assistant_text)
            tool_json_error = None if tool_block_error else self._tool_call_json_validation_error(assistant_text)
            if tool_block_error or tool_json_error:
                error_response = self._format_error_response(tool_block_error or tool_json_error)
                rollout_messages.append(assistant_record)
                history_messages.append(self._format_error_history_message(error_response))
                active_snapshot = self._state_local_snapshot(
                    build_harness_snapshot(history_messages, allow_legacy_python_budget=False)
                )
                next_user_prompt = self._compact_state_prompt(active_snapshot, history_messages)
                state_prompt_ids = await self.loop.run_in_executor(
                    None,
                    lambda: self.tokenizer.apply_chat_template(
                        [{"role": "user", "content": next_user_prompt}],
                        add_generation_prompt=True,
                        tokenize=True,
                    ),
                )
                if len(response_mask) + len(state_prompt_ids) >= self.response_length:
                    break
                rollout_messages.append(self._obs_record(error_response))
                prompt_ids += state_prompt_ids
                response_mask += [0] * len(state_prompt_ids)
                rollout_messages.append({"role": "user", "content": next_user_prompt})
                user_turns += 1
                continue

            tool_calls = await self.tool_parser.extract_tool_calls(response_ids)
            if not tool_calls:
                error_response = self._format_error_response({"error": "no_valid_tool_call"})
                rollout_messages.append(assistant_record)
                history_messages.append(self._format_error_history_message(error_response))
                active_snapshot = self._state_local_snapshot(
                    build_harness_snapshot(history_messages, allow_legacy_python_budget=False)
                )
                next_user_prompt = self._compact_state_prompt(active_snapshot, history_messages)
                state_prompt_ids = await self.loop.run_in_executor(
                    None,
                    lambda: self.tokenizer.apply_chat_template(
                        [{"role": "user", "content": next_user_prompt}],
                        add_generation_prompt=True,
                        tokenize=True,
                    ),
                )
                if len(response_mask) + len(state_prompt_ids) >= self.response_length:
                    break
                rollout_messages.append(self._obs_record(error_response))
                prompt_ids += state_prompt_ids
                response_mask += [0] * len(state_prompt_ids)
                rollout_messages.append({"role": "user", "content": next_user_prompt})
                user_turns += 1
                continue

            normalized_calls = self._normalize_tool_calls(tool_calls)
            assistant_record["tool_calls"] = [
                {"name": item["name"], "parameters": item["parameters"]} for item in normalized_calls
            ]
            rollout_messages.append(assistant_record)

            # call tools
            tasks = []
            task_indices = []
            tool_responses: list[dict[str, Any] | None] = [None] * len(normalized_calls)
            for idx, tool_call in enumerate(normalized_calls):
                validation_error = tool_block_error
                if validation_error is None and self.max_parallel_calls and idx >= self.max_parallel_calls:
                    validation_error = {
                        "error": "too_many_parallel_calls",
                        "tool": tool_call["name"],
                        "max_parallel_calls": self.max_parallel_calls,
                    }
                if validation_error is None:
                    validation_error = self._tool_validation_error(
                        tool_call,
                        normalized_calls,
                        active_snapshot,
                    )
                if validation_error:
                    tool_responses[idx] = self._tool_error_response(tool_call, validation_error)
                    continue
                task_indices.append(idx)
                tasks.append(self._call_tool(tool_call, active_snapshot))
            with simple_timer("tool_calls", metrics):
                executed_responses = await asyncio.gather(*tasks) if tasks else []
            if any(isinstance(item, Exception) for item in tool_responses):
                break
            for idx, item in zip(task_indices, executed_responses, strict=False):
                tool_responses[idx] = item
            if any(item is None or isinstance(item, Exception) for item in tool_responses):
                break
            tool_responses = [item for item in tool_responses if item is not None]

            history_messages.append(
                self._assistant_history_message(
                    assistant_text=assistant_text,
                    normalized_calls=normalized_calls,
                    tool_results=tool_responses,
                )
            )

            if any(self._is_successful_terminate(item) for item in tool_responses):
                for item in tool_responses:
                    rollout_messages.append(self._obs_record(item))
                break

            active_snapshot = self._state_local_snapshot(
                build_harness_snapshot(history_messages, allow_legacy_python_budget=False)
            )
            next_user_prompt = self._compact_state_prompt(active_snapshot, history_messages)
            state_prompt_ids = await self.loop.run_in_executor(
                None,
                lambda: self.tokenizer.apply_chat_template(
                    [{"role": "user", "content": next_user_prompt}],
                    add_generation_prompt=True,
                    tokenize=True,
                ),
            )

            # NOTE: last turn should not be user turn, or the EOS token reward
            # can't be propagated to previous token in GAE.
            if len(response_mask) + len(state_prompt_ids) >= self.response_length:
                break

            for item in tool_responses:
                rollout_messages.append(self._obs_record(item))
            prompt_ids += state_prompt_ids
            response_mask += [0] * len(state_prompt_ids)
            rollout_messages.append({"role": "user", "content": next_user_prompt})
            user_turns += 1

        response_ids = prompt_ids[-len(response_mask) :]
        prompt_ids = prompt_ids[: len(prompt_ids) - len(response_mask)]

        output = AgentLoopOutput(
            prompt_ids=prompt_ids,
            response_ids=response_ids[: self.response_length],
            response_mask=response_mask[: self.response_length],
            num_turns=user_turns + assistant_turns + 1,
            metrics=metrics,
            messages=rollout_messages,
        )
        return output

    def _state_local_snapshot(self, snapshot):
        if snapshot.state_name == STATE_CANDIDATE_SELECT:
            snapshot.include_tools = {"view_product_information", "budget_check"}
        max_failed = self.state_max_searches or 5
        if isinstance(snapshot.state, dict) and max_failed:
            if "failed_searches" in snapshot.state:
                snapshot.state["failed_searches"] = (snapshot.state.get("failed_searches") or [])[-max_failed:]
            if "failed_retry_searches" in snapshot.state:
                snapshot.state["failed_retry_searches"] = (snapshot.state.get("failed_retry_searches") or [])[-max_failed:]
        return snapshot

    def _compact_state_prompt(self, snapshot, history_messages: list[str]) -> str:
        max_candidates = self.state_max_budget_candidates or self.state_max_candidates_per_search
        return build_compact_harness_user_prompt(
            snapshot,
            history_messages,
            max_candidates=max_candidates,
            max_failed_searches=self.state_max_searches or 5,
            max_viewed_products=self.state_max_viewed_products,
        )

    def _sampling_params_for_remaining_response(
        self,
        sampling_params: dict[str, Any],
        *,
        used_response_tokens: int,
    ) -> dict[str, Any] | None:
        remaining = self.response_length - used_response_tokens
        params = dict(sampling_params)
        if remaining <= 0:
            return None
        for key in ("max_tokens", "max_new_tokens"):
            existing = params.get(key)
            params[key] = min(int(existing), remaining) if existing is not None else remaining
        return params

    def _truncate_tool_response(self, text: str) -> str:
        max_len = self.max_tool_response_length
        if not max_len or max_len <= 0:
            return text
        token_ids = self.tokenizer.encode(text, add_special_tokens=False)
        if len(token_ids) <= max_len:
            return text
        if self.tool_response_truncate_side == "left":
            token_ids = token_ids[-max_len:]
        elif self.tool_response_truncate_side == "middle":
            left_len = max_len // 2
            right_len = max_len - left_len
            token_ids = token_ids[:left_len] + token_ids[-right_len:]
        else:
            token_ids = token_ids[:max_len]
        return self.tokenizer.decode(token_ids)

    def _obs_message(self, item: dict[str, Any]) -> str:
        return f"<obs>{self._truncate_tool_response(item['tool_response'])}</obs>"

    def _obs_record(self, item: dict[str, Any]) -> dict[str, Any]:
        return {
            "role": "user",
            "content": self._obs_message(item),
            "obs": [
                {
                    "tool_call_id": item["tool_call_id"],
                    "results": item.get("result"),
                }
            ],
        }

    @staticmethod
    def _system_message(messages: list[dict[str, Any]]) -> dict[str, str]:
        runtime_system_prompt = getattr(ToolAgentLoop, "runtime_system_prompt", None)
        if runtime_system_prompt:
            return {"role": "system", "content": runtime_system_prompt}
        for message in messages:
            if message.get("role") == "system":
                return {"role": "system", "content": str(message.get("content") or "")}
        return {"role": "system", "content": ""}

    @staticmethod
    def _initial_user_query(messages: list[dict[str, Any]]) -> str:
        content = ""
        for message in messages:
            if message.get("role") == "user":
                content = str(message.get("content") or "")
                break
        match = re.search(r"<user>(.*?)</user>", content, flags=re.DOTALL)
        if match:
            return match.group(1).strip()
        return content.strip()

    @staticmethod
    def _extract_role_text(text: str, role: str) -> str:
        match = re.search(rf"<{role}>(.*?)</{role}>", text or "", flags=re.DOTALL)
        return match.group(1).strip() if match else ""

    @staticmethod
    def _parse_tool_response(tool_response: str):
        try:
            return json.loads(tool_response)
        except Exception:
            return tool_response

    @staticmethod
    def _selected_product_ids(snapshot) -> set[str]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        return {
            str(product.get("product_id"))
            for product in state.get("selected_products", [])
            if isinstance(product, dict) and product.get("product_id") is not None
        }

    @staticmethod
    def _budget_product_ids(snapshot) -> set[str]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        ids = state.get("budget_product_ids") or []
        return {str(product_id) for product_id in ids if product_id is not None}

    @staticmethod
    def _viewed_product_ids(snapshot) -> set[str]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        return {
            str(product.get("product_id"))
            for product in state.get("viewed_products", [])
            if isinstance(product, dict) and product.get("product_id") is not None
        }

    @staticmethod
    def _budget_result(snapshot) -> dict[str, Any]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        budget = state.get("budget_calculation") or {}
        return budget if isinstance(budget, dict) else {}

    @classmethod
    def _verified_shop_ids(cls, snapshot, product_ids: set[str]) -> set[str]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        shops = set()
        for product in state.get("selected_products", []):
            if not isinstance(product, dict):
                continue
            product_id = product.get("product_id")
            if product_id is not None and str(product_id) in product_ids and product.get("shop_id") is not None:
                shops.add(str(product.get("shop_id")))
        budget = cls._budget_result(snapshot)
        budget_ids = [str(item) for item in budget.get("product_ids") or [] if item is not None]
        budget_shops = [str(item) for item in budget.get("shop_ids") or [] if item is not None]
        for product_id, shop_id in zip(budget_ids, budget_shops):
            if product_id in product_ids:
                shops.add(shop_id)
        return shops

    @classmethod
    def _budget_agent_voucher_requires_single_shop(cls, snapshot) -> bool:
        voucher = cls._budget_result(snapshot).get("agent_voucher") or {}
        if not isinstance(voucher, dict):
            return False
        voucher_type = str(voucher.get("type", "")).lower()
        return "shop" in voucher_type or bool(voucher.get("scope_shop_id") or voucher.get("shop_id"))

    @staticmethod
    def _unique_tool_call_id(name: str, parameters: dict[str, Any], used_ids: set[str]) -> str:
        base_id = generate_tool_call_id(name, parameters)
        tool_call_id = base_id
        suffix = 1
        while tool_call_id in used_ids:
            suffix += 1
            tool_call_id = f"{base_id}_{suffix}"
        used_ids.add(tool_call_id)
        return tool_call_id

    def _normalize_tool_calls(self, tool_calls: list[FunctionCall]) -> list[dict[str, Any]]:
        normalized = []
        used_ids: set[str] = set()
        for tool_call in tool_calls:
            try:
                parameters = json.loads(tool_call.arguments)
            except Exception:
                parameters = {}
            if not isinstance(parameters, dict):
                parameters = {}
            normalized.append(
                {
                    "name": tool_call.name,
                    "parameters": parameters,
                    "tool_call_id": self._unique_tool_call_id(tool_call.name, parameters, used_ids),
                }
            )
        return normalized

    def _assistant_history_message(
        self,
        assistant_text: str,
        normalized_calls: list[dict[str, Any]],
        tool_results: list[dict[str, Any]],
    ) -> str:
        obs = [
            {
                "tool_call_id": call["tool_call_id"],
                "results": result["result"],
            }
            for call, result in zip(normalized_calls, tool_results, strict=False)
        ]
        message = Message(
            think=self._extract_role_text(assistant_text, "think"),
            tool_call=normalized_calls,
            obs=obs,
            response=self._extract_role_text(assistant_text, "response"),
        )
        return message.to_string(ASSISTANT_ROLES)

    @staticmethod
    def _is_decision_tool_set(allowed_tools: set[str]) -> bool:
        return {"find_product", "recommend_product", "terminate"}.issubset(allowed_tools)

    @staticmethod
    def _strip_generation_markers(text: str) -> str:
        if "<|im_start|>assistant" in text:
            text = text.split("<|im_start|>assistant")[-1]
        for marker in ("<|im_end|>", "<|endoftext|>"):
            if marker in text:
                text = text.split(marker)[0]
        return text.strip()

    @staticmethod
    def _tool_block_validation_error(text: str) -> dict[str, Any] | None:
        text = ToolAgentLoop._strip_generation_markers(text or "")
        if text.count("<think>") != 1 or text.count("</think>") != 1:
            return {"error": "exactly_one_think_block_required"}
        if text.count("<tool_call>") != 1 or text.count("</tool_call>") != 1:
            return {"error": "exactly_one_tool_call_block_required"}
        if text.find("</think>") > text.find("<tool_call>"):
            return {"error": "think_block_must_precede_tool_call_block"}
        pattern = re.compile(r"^\s*<think>.*?</think>\s*<tool_call>.*?</tool_call>\s*$", re.DOTALL)
        if not pattern.match(text):
            return {"error": "state_local_output_must_be_think_then_tool_call_only"}
        think_match = re.search(r"<think>(.*?)</think>", text, re.DOTALL)
        if not think_match or not think_match.group(1).strip():
            return {"error": "think_block_must_be_non_empty"}
        return None

    @staticmethod
    def _tool_call_json_validation_error(text: str) -> dict[str, Any] | None:
        text = ToolAgentLoop._strip_generation_markers(text or "")
        match = re.search(r"<tool_call>(.*?)</tool_call>", text, re.DOTALL)
        if not match:
            return {"error": "exactly_one_tool_call_block_required"}
        try:
            parsed = json.loads(match.group(1).strip())
        except Exception:
            return {"error": "tool_call_json_must_be_valid_array"}
        if not isinstance(parsed, list):
            if isinstance(parsed, dict) and set(parsed.keys()) == {"name", "arguments"}:
                return {"error": "tool_call_must_use_parameters_array_not_arguments_object"}
            return {"error": "tool_call_must_be_json_array"}
        if not parsed:
            return {"error": "tool_call_array_must_be_non_empty"}
        for item in parsed:
            if isinstance(item, dict) and "arguments" in item:
                return {"error": "tool_call_must_use_parameters_not_arguments"}
            if not isinstance(item, dict) or set(item.keys()) != {"name", "parameters"}:
                return {"error": "tool_call_items_require_exactly_name_and_parameters"}
            if not isinstance(item.get("name"), str) or not isinstance(item.get("parameters"), dict):
                return {"error": "tool_call_name_string_parameters_object_required"}
        return None

    @classmethod
    def _tool_validation_error(
        cls,
        tool_call: dict[str, Any],
        all_calls: list[dict[str, Any]],
        snapshot,
    ) -> dict[str, Any] | None:
        allowed_tools = snapshot.include_tools
        tool_names = {call["name"] for call in all_calls}
        parameters = tool_call.get("parameters") or {}
        if tool_call["name"] == "find_product":
            if not parameters.get("q") or parameters.get("page") in (None, ""):
                return {
                    "error": "find_product_requires_q_and_page",
                    "tool": tool_call["name"],
                    "required_fix": 'Use parameters {"q": string, "page": integer}.',
                }
            sort = parameters.get("sort")
            if sort not in (None, "", "priceasc", "pricedesc", "order", "default"):
                return {
                    "error": "find_product_invalid_sort",
                    "tool": tool_call["name"],
                    "required_fix": 'Use sort only as one of "priceasc", "pricedesc", "order", or "default".',
                }
            service = parameters.get("service")
            if service:
                allowed_services = {"official", "freeShipping", "COD", "flashsale", "default"}
                invalid_services = [
                    item.strip()
                    for item in str(service).split(",")
                    if item.strip() and item.strip() not in allowed_services
                ]
                if invalid_services:
                    return {
                        "error": "find_product_invalid_service",
                        "tool": tool_call["name"],
                        "invalid_service_values": invalid_services,
                        "required_fix": 'Use service values exactly from "COD", "freeShipping", "flashsale", "official", joined by comma if needed.',
                    }
        elif tool_call["name"] == "view_product_information":
            if not parameters.get("product_ids"):
                return {
                    "error": "view_product_information_requires_product_ids",
                    "tool": tool_call["name"],
                    "required_fix": 'Use parameters {"product_ids": "id1,id2"}.',
                }
        elif tool_call["name"] == "budget_check":
            if not parameters.get("product_ids") or parameters.get("budget") in (None, ""):
                return {
                    "error": "budget_check_requires_product_ids_and_budget",
                    "tool": tool_call["name"],
                    "required_fix": 'Use parameters {"product_ids": [string, ...], "voucher": object, "budget": number}.',
                }
        elif tool_call["name"] == "recommend_product":
            if not parameters.get("product_ids"):
                return {
                    "error": "recommend_product_requires_product_ids",
                    "tool": tool_call["name"],
                    "required_fix": 'Use parameters {"product_ids": "id1,id2"}.',
                }
        elif tool_call["name"] == "terminate":
            if parameters.get("status") != "success":
                return {
                    "error": "terminate_status_must_be_success",
                    "tool": tool_call["name"],
                    "required_fix": 'Use parameters {"status": "success"}.',
                }
        if snapshot.state_name == STATE_CANDIDATE_SELECT and "budget_check" in tool_names:
            if "view_product_information" not in tool_names:
                return {
                    "error": "budget_check_requires_view_product_information_in_select",
                    "tool": "selection",
                    "required_fix": "Call view_product_information and budget_check for the same selected product ids in the same turn.",
                }
            view_ids = []
            budget_ids = []
            for call in all_calls:
                if call["name"] == "view_product_information":
                    view_ids.extend(cls._parse_product_ids_param(call.get("parameters", {}).get("product_ids")))
                elif call["name"] == "budget_check":
                    budget_ids.extend(cls._parse_product_ids_param(call.get("parameters", {}).get("product_ids")))
            if view_ids and budget_ids and set(view_ids) != set(budget_ids):
                return {
                    "error": "view_and_budget_product_ids_must_match",
                    "tool": "selection",
                    "view_product_ids": view_ids,
                    "budget_product_ids": budget_ids,
                    "required_fix": "Use the exact same selected product ids in view_product_information and budget_check.",
                }
        if cls._is_decision_tool_set(allowed_tools):
            if "find_product" in tool_names and bool({"recommend_product", "terminate"} & tool_names):
                return {
                    "error": "mixed_decision_actions_not_allowed",
                    "tool": "decision",
                    "required_fix": "In DECISION, either call recommend_product plus terminate, or call only find_product.",
                }
            if "terminate" in tool_names and "recommend_product" not in tool_names:
                if tool_call["name"] == "terminate":
                    return {
                        "error": "terminate_requires_recommend_product_in_decision",
                        "tool": tool_call["name"],
                        "required_fix": "Call recommend_product and terminate in the same tool_call array.",
                    }
            if "recommend_product" in tool_names and "terminate" not in tool_names:
                if tool_call["name"] == "recommend_product":
                    return {
                        "error": "recommend_product_requires_terminate_in_decision",
                        "tool": tool_call["name"],
                        "required_fix": "Call recommend_product and terminate in the same tool_call array.",
                    }
            if tool_call["name"] == "terminate":
                expected_ids = cls._budget_product_ids(snapshot) or cls._selected_product_ids(snapshot)
                recommend_calls = [call for call in all_calls if call["name"] == "recommend_product"]
                if len(recommend_calls) != 1:
                    return {
                        "error": "terminate_requires_exactly_one_recommend_product_in_same_turn",
                        "tool": tool_call["name"],
                        "recommend_product_call_count": len(recommend_calls),
                        "required_fix": "Use exactly one recommend_product call before terminate in the same tool_call array.",
                    }
                if recommend_calls:
                    recommended_list = cls._parse_product_ids_param(
                        (recommend_calls[0].get("parameters") or {}).get("product_ids")
                    )
                    recommended_ids = set(recommended_list)
                    if not recommended_ids or len(recommended_list) != len(recommended_ids) or (
                        expected_ids and recommended_ids != expected_ids
                    ):
                        return {
                            "error": "terminate_requires_valid_recommend_product_in_same_turn",
                            "tool": tool_call["name"],
                            "recommended_product_ids": sorted(recommended_ids),
                            "expected_product_ids": sorted(expected_ids),
                            "required_fix": "Recommend exactly the product ids from the verified selection.",
                        }
            if tool_call["name"] == "recommend_product":
                recommended_list = cls._parse_product_ids_param((tool_call.get("parameters") or {}).get("product_ids"))
                recommended_ids = set(recommended_list)
                selected_ids = cls._selected_product_ids(snapshot)
                budget_ids = cls._budget_product_ids(snapshot)
                expected_ids = budget_ids or selected_ids
                if not recommended_ids:
                    return {
                        "error": "recommend_product_requires_product_ids",
                        "tool": tool_call["name"],
                        "required_fix": 'Use parameters {"product_ids": "id1,id2"}.',
                    }
                if len(recommended_list) != len(recommended_ids):
                    return {
                        "error": "recommend_product_duplicate_product_ids",
                        "tool": tool_call["name"],
                        "recommended_product_ids": recommended_list,
                        "required_fix": "Recommend each verified product id exactly once.",
                    }
                if expected_ids and len(recommended_ids) != len(expected_ids):
                    return {
                        "error": "recommend_product_product_count_mismatch",
                        "tool": tool_call["name"],
                        "recommended_product_ids": sorted(recommended_ids),
                        "expected_product_ids": sorted(expected_ids),
                        "required_fix": "Recommend exactly the same number of product ids as the verified budget_check selection.",
                    }
                if expected_ids and recommended_ids != expected_ids:
                    return {
                        "error": "recommend_product_ids_must_match_verified_selection",
                        "tool": tool_call["name"],
                        "recommended_product_ids": sorted(recommended_ids),
                        "expected_product_ids": sorted(expected_ids),
                        "required_fix": "Recommend exactly the product ids from the verified selection.",
                    }
                viewed_ids = cls._viewed_product_ids(snapshot)
                missing_view = sorted(product_id for product_id in recommended_ids if product_id not in viewed_ids)
                if missing_view:
                    return {
                        "error": "recommend_requires_viewed_product_evidence",
                        "tool": tool_call["name"],
                        "recommended_product_ids": sorted(recommended_ids),
                        "missing_viewed_product_ids": missing_view,
                        "required_fix": "Call view_product_information for every recommended product id before recommending.",
                    }
                if cls._budget_agent_voucher_requires_single_shop(snapshot):
                    shops = cls._verified_shop_ids(snapshot, recommended_ids)
                    if len(shops) != 1:
                        return {
                            "error": "shop_voucher_recommend_requires_single_shop",
                            "tool": tool_call["name"],
                            "recommended_product_ids": sorted(recommended_ids),
                            "shop_ids": sorted(shops),
                            "required_fix": "For a shop voucher, recommend only products verified from one shop or search for a same-shop bundle.",
                        }
        if tool_call["name"] not in allowed_tools:
            return {
                "error": "tool_not_allowed_in_current_state",
                "tool": tool_call["name"],
                "allowed_tools": sorted(allowed_tools),
                "required_fix": "Choose a tool from allowed_tools only.",
            }
        if tool_call["name"] == "find_product" and is_repeated_failed_search(tool_call.get("parameters", {}), snapshot):
            return {
                "error": "repeated_failed_search_not_allowed",
                "tool": tool_call["name"],
                "required_fix": "Change the search parameters before retrying.",
            }
        if tool_call["name"] == "find_product" and is_duplicate_find_product_in_turn(tool_call, all_calls):
            return {
                "error": "duplicate_find_product_in_same_turn_not_allowed",
                "tool": tool_call["name"],
                "required_fix": "Do not repeat the same find_product parameters within one tool_call array.",
            }
        if tool_call["name"] == "find_product" and is_repeated_search(tool_call.get("parameters", {}), snapshot):
            return {
                "error": "repeated_search_not_allowed",
                "tool": tool_call["name"],
                "required_fix": "Use a new q, page, shop_id, price, sort, or service value.",
            }
        return None

    @staticmethod
    def _tool_error_response(tool_call: dict[str, Any], error: dict[str, Any]) -> dict[str, Any]:
        return {
            "tool_call_id": tool_call["tool_call_id"],
            "name": tool_call["name"],
            "parameters": tool_call["parameters"],
            "tool_response": json.dumps(error, ensure_ascii=False),
            "result": error,
        }

    @staticmethod
    def _format_error_response(error: dict[str, Any]) -> dict[str, Any]:
        payload = {"tool": "format", **error}
        payload.setdefault("required_fix", ToolAgentLoop._format_required_fix(payload.get("error")))
        payload.setdefault("required_format", ToolAgentLoop._format_required_format())
        return {
            "tool_call_id": "format_error",
            "name": "format",
            "parameters": {},
            "tool_response": json.dumps(payload, ensure_ascii=False),
            "result": payload,
        }

    @staticmethod
    def _format_required_format() -> str:
        return '<think>brief reasoning</think><tool_call>[{"name":"allowed_tool","parameters":{}}]</tool_call>'

    @staticmethod
    def _format_required_fix(error: str | None) -> str:
        fixes = {
            "empty_model_content": "Output a non-empty <think>...</think><tool_call>...</tool_call> message.",
            "exactly_one_think_block_required": "Output exactly one opening <think> and one closing </think> before <tool_call>.",
            "exactly_one_tool_call_block_required": "Output exactly one opening <tool_call> and one closing </tool_call> after <think>. Do not use XML tags like <find_product>, function-call syntax, markdown, or natural language outside the blocks.",
            "think_block_must_precede_tool_call_block": "Place <think>...</think> before <tool_call>...</tool_call>.",
            "state_local_output_must_be_think_then_tool_call_only": "Output only <think>...</think><tool_call>...</tool_call>, with no text outside the tags.",
            "think_block_must_be_non_empty": "Put concise reasoning inside <think>...</think>.",
            "tool_call_json_must_be_valid_array": 'Inside <tool_call> must be raw JSON array only, for example [{"name":"find_product","parameters":{"q":"...","page":1}}]. Do not use XML tags like <find_product> or <function=...>.',
            "tool_call_must_be_json_array": 'The <tool_call> content must be a JSON array [...] not a single object {...}. Wrap one call as [{"name":"allowed_tool","parameters":{}}].',
            "tool_call_must_use_parameters_array_not_arguments_object": 'Do not use Qwen/OpenAI native function-call shape. Use a JSON array and the key "parameters": [{"name":"allowed_tool","parameters":{}}].',
            "tool_call_must_use_parameters_not_arguments": 'Use the ShoppingBench key "parameters", not "arguments". Each item must be {"name":"allowed_tool","parameters":{}}.',
            "tool_call_array_must_be_non_empty": "Include at least one tool call object in the JSON array.",
            "tool_call_items_require_exactly_name_and_parameters": 'Each tool call object must contain exactly "name" and "parameters"; do not use "arguments" or "tool_call_id".',
            "tool_call_name_string_parameters_object_required": '"name" must be a string and "parameters" must be an object.',
            "no_valid_tool_call": "Use the exact tool_call schema from the prompt with allowed tool names; do not output OpenAI function-call syntax or XML tool tags.",
        }
        return fixes.get(error or "", "Fix the output format and retry.")

    @staticmethod
    def _format_error_history_message(error_response: dict[str, Any]) -> str:
        message = Message(
            obs=[
                {
                    "tool_call_id": error_response["tool_call_id"],
                    "results": error_response["result"],
                }
            ]
        )
        return message.to_string(ASSISTANT_ROLES)

    @staticmethod
    def _is_error_result(result) -> bool:
        return isinstance(result, dict) and "error" in result

    @staticmethod
    def _is_successful_terminate(item: dict[str, Any]) -> bool:
        if item.get("name") != "terminate":
            return False
        result = item.get("result")
        return (
            isinstance(result, dict)
            and result.get("status") == "success"
            and result.get("_tool_success") is True
        )

    async def _call_tool(self, tool_call: dict[str, Any], snapshot=None) -> dict[str, Any]:
        """Call tool and return tool response."""
        if tool_call["name"] == "budget_check":
            return self._budget_check_response(tool_call, snapshot)

        tool, instance_id = None, None
        try:
            # TODO: append malformed tool_call to the prompt: invalid function name or arguments
            tool_name = tool_call["name"]
            tool_args = tool_call["parameters"]
            tool = self.tools[tool_name]

            instance_id = await tool.create()
            tool_response, _, _ = await tool.execute(instance_id, tool_args)
        except Exception as e:
            logger.exception(f"Error when executing tool: {e}")
            return e
        finally:
            if tool and instance_id:
                await tool.release(instance_id)

        return {
            "tool_call_id": tool_call["tool_call_id"],
            "name": tool_call["name"],
            "parameters": tool_call["parameters"],
            "tool_response": tool_response,
            "result": self._parse_tool_response(tool_response),
        }

    @staticmethod
    def _parse_product_ids_param(value) -> list[str]:
        if isinstance(value, list):
            return [str(item) for item in value if item not in (None, "")]
        if isinstance(value, str):
            return [part.strip() for part in value.split(",") if part.strip()]
        return []

    @staticmethod
    def _float_or_none(value):
        try:
            return float(value)
        except Exception:
            return None

    @classmethod
    def _products_for_budget_check(cls, product_ids: list[str], snapshot) -> tuple[list[dict[str, Any]], dict | None]:
        state = snapshot.state if snapshot is not None and isinstance(snapshot.state, dict) else {}
        products_by_id = {}
        for product in state.get("candidate_pool") or []:
            if isinstance(product, dict) and product.get("product_id") is not None:
                products_by_id[str(product["product_id"])] = product
        missing = [product_id for product_id in product_ids if product_id not in products_by_id]
        if missing:
            return [], {"error": "budget_check_product_ids_not_in_candidate_pool", "missing_product_ids": missing}
        products = [products_by_id[product_id] for product_id in product_ids]
        if len(product_ids) != len(set(product_ids)):
            return [], {"error": "budget_check_duplicate_product_ids"}
        for product in products:
            if cls._float_or_none(product.get("price")) is None or product.get("shop_id") is None:
                return [], {"error": "budget_check_missing_price_or_shop_id"}
        return products, None

    @classmethod
    def _compute_voucher_discount(cls, products: list[dict[str, Any]], voucher: dict[str, Any]) -> tuple[float, bool, dict | None]:
        if not isinstance(voucher, dict):
            voucher = {"type": "none"}
        voucher_type = str(voucher.get("type", "none")).lower()
        if voucher_type in {"none", "no_voucher", "null"}:
            return 0.0, False, None

        prices = [float(product["price"]) for product in products]
        total = sum(prices)
        scope_shop_id = voucher.get("scope_shop_id") or voucher.get("shop_id")
        if "shop" in voucher_type or scope_shop_id:
            if scope_shop_id is None:
                selected_shops = {str(product.get("shop_id")) for product in products}
                if len(selected_shops) != 1:
                    return 0.0, False, {"error": "shop_voucher_requires_single_shop_or_scope_shop_id"}
                scope_shop_id = next(iter(selected_shops))
            eligible_total = sum(
                float(product["price"])
                for product in products
                if str(product.get("shop_id")) == str(scope_shop_id)
            )
        else:
            eligible_total = total

        threshold = cls._float_or_none(voucher.get("threshold"))
        if threshold is not None and eligible_total + 1e-9 < threshold:
            return 0.0, False, None

        discount = cls._float_or_none(voucher.get("discount"))
        if discount is None:
            discount = cls._float_or_none(voucher.get("amount"))
        if discount is None:
            discount = cls._float_or_none(voucher.get("value"))
        rate = cls._float_or_none(voucher.get("rate"))
        cap = cls._float_or_none(voucher.get("cap"))
        if rate is not None:
            if rate > 1:
                rate = rate / 100.0
            discount = eligible_total * rate
            if cap is not None:
                discount = min(discount, cap)
        if discount is None:
            return 0.0, False, {"error": "unsupported_voucher_schema"}
        discount = max(0.0, min(float(discount), eligible_total))
        return discount, discount > 0, None

    def _budget_check_response(self, tool_call: dict[str, Any], snapshot) -> dict[str, Any]:
        parameters = tool_call.get("parameters") or {}
        product_ids = self._parse_product_ids_param(parameters.get("product_ids"))
        products, error = self._products_for_budget_check(product_ids, snapshot)
        if error is None and not product_ids:
            error = {"error": "budget_check_requires_product_ids"}

        if error is None:
            voucher = parameters.get("voucher") or {"type": "none"}
            discount, voucher_used, error = self._compute_voucher_discount(products, voucher)
        if error is None and self._float_or_none(parameters.get("budget")) is None:
            error = {"error": "budget_check_requires_numeric_budget"}

        if error is not None:
            result = {
                **error,
                "_tool_success": False,
                "_parse_ok": True,
            }
        else:
            budget = self._float_or_none(parameters.get("budget"))
            total = round(sum(float(product["price"]) for product in products), 2)
            payable_total = round(max(0.0, total - discount), 2)
            result = {
                "product_ids": product_ids,
                "shop_ids": [str(product.get("shop_id")) for product in products],
                "total_before_voucher": total,
                "voucher_used": bool(voucher_used),
                "voucher_applied": bool(voucher_used),
                "payable_total": payable_total,
                "budget": budget,
                "within_budget": payable_total <= budget,
                "agent_voucher": parameters.get("voucher") or {"type": "none"},
                "_tool_success": True,
                "_parse_ok": True,
            }
        tool_response = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
        return {
            "tool_call_id": tool_call["tool_call_id"],
            "name": tool_call["name"],
            "parameters": parameters,
            "tool_response": tool_response,
            "result": result,
        }

    @classmethod
    def get_tool_parser(cls, name: str) -> ToolParser:
        tool_parsers = {
            "hermes": HermesToolParser,
            "shoppingbench_xml": ShoppingBenchXMLToolParser,
        }
        if name not in tool_parsers:
            raise ValueError(f"Unknown tool parser: {name}")
        return tool_parsers[name](cls.tokenizer)
